import swaggerAutogen from "swagger-autogen";
import { expressOptions } from "../env.js";

const docConfig = {
  openapi: "3.0.0",
  info: {
    version: "1.0.0",
    title: "BidsHandler API Documentation (OpenAPIv3)",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  servers: [
    {
      url: `http://${expressOptions.host}:${expressOptions.port}`,
      description: "API server",
    },
  ],
  tags: [
    {
      name: "Greeting",
      description: "Start page of the API",
    },
    {
      name: "Reg&Auth",
      description: "Registration & authentication end-points",
    },
    {
      name: "Bids",
      description: "Bids end-points",
    },
    {
      name: "Redirect",
      description: "Redirect to the API home page",
    },
  ],
  components: {
    "@schemas": {
      RequestSignUpSchema: {
        type: "object",
        required: ["username", "email", "password"],
        properties: {
          username: {
            type: "string",
            example: "John_Doe",
            description: "Users username",
          },
          firstName: {
            type: "string",
            example: "John",
            description: "Users First name",
          },
          lastName: {
            type: "string",
            example: "Doe",
            description: "Users Last name",
          },
          email: {
            type: "string",
            example: "QKx0o@example.com",
            description: "Users email",
          },
          password: {
            type: "string",
            example: "12345678",
            description: "Users password",
          },
          gender: {
            type: "string",
            example: "male",
            description: "Users gender",
          },
          isAdmin: {
            type: "boolean",
            example: true,
            description: "Users role",
          },
          avatar: {
            type: "string",
            format: "binary",
            description: "Users avatar file in multipart",
          },
        },
      },
      RequestSignInSchema: {
        type: "object",
        required: ["password"],
        oneOf: [
          {
            required: ["username"],
            properties: {
              username: {
                type: "string",
                example: "John_Doe",
                description: "Users username",
              },
            },
          },
          {
            required: ["email"],
            properties: {
              email: {
                type: "string",
                example: "QKx0o@example.com",
                description: "Users email",
              },
            },
          },
        ],
        properties: {
          password: {
            type: "string",
            example: "12345678",
            description: "Users password",
          },
        },
      },
      ResponseSuccessfulAuthenticationRefreshSchema: {
        type: "object",
        required: ["accessToken"],
        properties: {
          accessToken: {
            type: "string",
            example: "eyJhbGciOiJIUz...",
            description: "Access token",
          },
        },
      },
      Response400Schema: {
        type: "object",
        required: ["message"],
        properties: {
          message: {
            type: "string",
            example: "Bad Request",
            description: "Error message",
          },
        },
      },
      Response401Schema: {
        type: "object",
        required: ["message"],
        properties: {
          message: {
            type: "string",
            example: "Unauthorized!",
            description: "Error message",
          },
        },
      },
      Response404Schema: {
        type: "object",
        required: ["message"],
        properties: {
          message: {
            type: "string",
            example: "Not found!",
            description: "Error message",
          },
        },
      },
    },
  },
};

const outputFile = "../docs/swagger-output.json";
const endpointsFiles = ["../server.js"];

swaggerAutogen({
  openapi: "3.0.0",
})(outputFile, endpointsFiles, docConfig);
